Repository DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank, pull requests merged in 2023-11, with the labels that each got.

#77 [Feat] 76 feat modal video black area 제거
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/Resources/insert.mov
  Blank/Blank/View/OCREdit/PlayerUIView.swift
  Blank/Blank/View/OCREdit/ScrribleModalView.swift
  Blank/Blank/View/OCREdit/ScrribleType.swift
  Blank/Blank/View/OCREdit/ScrribleVideoView.swift
Labels: enhancement

#78 [Feat] N회차 표시
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/CoreData/CDService.swift
  Blank/Blank/Extension/Double.swift
  Blank/Blank/Model/Presentable/SessionStatistics.swift
  Blank/Blank/Model/Presentable/WordStatistics.swift
  Blank/Blank/View/CorrectInfoView.swift
  Blank/Blank/View/Home/HomeView.swift
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/View/OverView/OverViewImageView.swift
  Blank/Blank/View/OverView/OverViewPinchZoomView.swift
  Blank/Blank/View/ResultPageView.swift
  Blank/Blank/ViewModel/OverViewModel.swift
  Blank/Blank/ViewModel/ScoringViewModel.swift
Labels: enhancement

#81 [Feat] 결과 보기 페이지에서 오답을 클릭했을 경우 원래 답을 표시하도록 변경
  Blank/Blank/View/ImageView.swift
  Blank/Blank/View/ResultPageView.swift
  Blank/Blank/View/WordSelectView.swift
Labels: enhancement, design

#86 [Fix/Refactoring] 오버뷰에서 페이지 전환 안되는 문제 수정
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OverView/OverVIewImageView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/View/ResultPageView.swift
  Blank/Blank/View/TestPage/TestPageView.swift
  Blank/Blank/View/WordSelectView.swift
  Blank/Blank/ViewModel/OverViewModel.swift
  Blank/Blank/ViewModel/ScoringViewModel.swift
  Blank/Blank/ViewModel/WordSelectViewModel.swift
Labels: bug, enhancement

#90 [feat] WordSelect drag gesture방식 구현
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/View/ImageView.swift
  Blank/Blank/View/ResultPageView.swift
  Blank/Blank/View/WordSelectView.swift
Labels: enhancement

#91 85 feat n회차일때 시험준비를 눌렀을때 alert가 나와 3가지 옵션을 주는 기능
  Blank/Blank/Util/ZoomableContainer.swift
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OCREdit/TextView.swift
  Blank/Blank/View/OverView/OverVIewImageView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/View/ResultPageView.swift
  Blank/Blank/View/TestPage/TestPageView.swift
  Blank/Blank/View/WordSelectView.swift
  Blank/Blank/ViewModel/OverViewModel.swift
  Blank/Blank/ViewModel/WordSelectViewModel.swift
Labels: enhancement

#95 93 feat bug textfield viewmodel 적용 및 버그 픽스
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OCREdit/OCRImageView.swift
  Blank/Blank/View/OCREdit/ScrribleModalView.swift
  Blank/Blank/View/OCREdit/ScrribleVideoView.swift
  Blank/Blank/View/OCREdit/TextView.swift
  Blank/Blank/View/TestPage/TestPageImageView.swift
  Blank/Blank/View/TestPage/TestPageView.swift
Labels: bug, enhancement

#98 [Fix] Overview에서 이미지 불러오기 최적화
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/View/OverView/OverVIewImageView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/ViewModel/OverViewModel.swift
Labels: bug

#97 92 feat 오버뷰모달뷰에 마지막세션 정보 연동
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/CoreData/CDService.swift
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OCREdit/ScrribleVideoView.swift
  Blank/Blank/View/OverView/OverViewModalView.swift
  Blank/Blank/View/ResultPage/CorrectInfoView.swift
  Blank/Blank/View/ResultPage/ResultPageView.swift
  Blank/Blank/ViewModel/OverViewModel.swift
Labels: enhancement

#100 [Feat] 워드셀렉트뷰에서 단어가 하나라도 선택되어야 다음 페이지로 이동가능하게 구현
  Blank/Blank/View/ImageView.swift
  Blank/Blank/View/OverView/OverViewModalView.swift
  Blank/Blank/View/WordSelectView.swift
Labels: enhancement

#102 [Feat] 오버뷰에서 결과보기 클릭시 내가 클릭한 회차를 버튼 라벨에 보여지게함
  Blank/Blank/View/OverView/OverView.swift
Labels: enhancement

#105 [Feat] OverView에서 페이지 전환시 표시 영역 지움 + '원본' 기능 구현
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/ViewModel/OverViewModel.swift
Labels: bug, enhancement

#106 [Fix] 오버뷰에서 키보드가 화면을 잡아먹으면서 뜨지 않게 버그 수정
  Blank/Blank/View/OverView/OverView.swift
Labels: bug

#109 96 bug moalview 리팩토링
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OCREdit/PlayerUIView.swift
  Blank/Blank/View/OCREdit/ScribbleModalView.swift
  Blank/Blank/View/OCREdit/ScribbleType.swift
  Blank/Blank/View/OCREdit/ScribbleVideoView.swift
  Blank/Blank/View/TestPage/TestPageImageView.swift
  Blank/Blank/View/TestPage/TestPageView.swift
  Blank/Blank/ViewModel/PlayerViewModel.swift
Labels: enhancement

#114 [Enhancement] 글자 인식시 좌표 연산 부분 개선완료
  Blank/Blank/Util/RecognizeText.swift
Labels: enhancement

#116 [feat] pencil double tap시 단어선택- 선택지우기 버튼간 변환구현
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/Util/PencilDobuleTapInteractionView.swift
  Blank/Blank/View/WordSelectView.swift
Labels: enhancement

#121 [Feat] 이미지 여백 늘리기 기능
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/BlankApp.swift
  Blank/Blank/Util/ImageUtil.swift
  Blank/Blank/Util/RecognizeText.swift
  Blank/Blank/ViewModel/OverViewModel.swift
Labels: enhancement

#120 #119 design 버튼에 테두리 추가
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/Contents.json
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-20@2x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-20@3x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-29@2x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-29@3x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-38@2x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-38@3x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-40@2x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-40@3x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-60@2x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-60@3x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-64@2x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-64@3x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-68@2x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-76@2x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/icon-83_5@2x.png
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/ios-marketing.png
  Blank/Blank/Assets.xcassets/Contents.json
  Blank/Blank/CoreData/CDService.swift
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/View/ResultPage/ResultPageView.swift
  Blank/Blank/View/TestPage/TestPageView.swift
  Blank/Blank/View/WordSelectView.swift
Labels: design

#122 111 feat tipkit 기능 추가
  Blank/Blank/Assets.xcassets/Contents.json
  Blank/Blank/Assets.xcassets/pencil.and.scribble.imageset/Contents.json
  Blank/Blank/Assets.xcassets/pencil.and.scribble.imageset/pencil.and.scribble.svg
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OCREdit/PlayerUIView.swift
  Blank/Blank/View/OCREdit/ScribbleType.swift
  Blank/Blank/View/OCREdit/ScribbleVideoView.swift
  Blank/Blank/ViewModel/PlayerViewModel.swift
Labels: bug, enhancement

#123 [feat] 기기별 좌표대응 수동 구현 완료
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/Resources/TestA.pdf
  Blank/Blank/Resources/TestB.pdf
  Blank/Blank/Resources/TestC.pdf
  Blank/Blank/Util/RecognizeText.swift
  Blank/Blank/View/ImageView.swift
  Blank/Blank/View/OCREdit/OCRImageView.swift
  Blank/Blank/View/OverView/OverVIewImageView.swift
  Blank/Blank/View/TestPage/TestPageImageView.swift
  Blank/Blank/View/WordSelectView.swift
  Blank/Blank/ViewModel/HomeViewModel.swift
  Blank/Blank/ViewModel/OverViewModel.swift
Labels: enhancement

#125 [Fix] loadLastSessionNumber 배열 범위초과 에러 해결
  Blank/Blank/ViewModel/OverViewModel.swift
Labels: bug

#128 [Bug] fontsize 가변적으로 적용
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/View/OCREdit/TextView.swift
  Blank/Blank/View/OverView/OverView.swift
Labels: bug

#135 [Fix] OverView: 전체통계 전환시 수치 누적 에러
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/Assets.xcassets/AppIcon.appiconset/Contents.json
  Blank/Blank/Assets.xcassets/PopoverShape.imageset/Contents.json
  Blank/Blank/Assets.xcassets/PopoverShape.imageset/PopoverShape.png
  Blank/Blank/Resources/ame.pdf
  Blank/Blank/Util/ZoomableContainer.swift
  Blank/Blank/View/ImageView.swift
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OCREdit/OCRImageView.swift
  Blank/Blank/View/OverView/OverVIewImageView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/View/TestPage/TestPageImageView.swift
  Blank/Blank/View/TestPage/TestPageView.swift
  Blank/Blank/ViewModel/OverViewModel.swift
Labels: bug

#137 134 feat ocreditview 원본 토글 만들기
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OCREdit/OCRImageView.swift
  Blank/Blank/ViewModel/WordSelectViewModel.swift
Labels: enhancement

#139 138 feat textfield view touch시 키보드 내리기
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/Extension/View+.swift
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/TestPage/TestPageView.swift
Labels: enhancement

#140 #133 design UI변경
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/View/Home/HomeView.swift
  Blank/Blank/View/ImageView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/View/PDFThumbnailView.swift
  Blank/Blank/View/ResultPage/ResultPageView.swift
  Blank/Blank/ViewModel/HomeViewModel.swift
Labels: design

#142 [Feat] 폴더 관련 기능 - 표시, 생성, 이동, 삭제
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/CoreData/CDService.swift
  Blank/Blank/Dummy/DummyObjects.swift
  Blank/Blank/Extension/FileMananger+.swift
  Blank/Blank/Model/FileSystem/File.swift
  Blank/Blank/Model/FileSystem/FileSystem.swift
  Blank/Blank/Model/FileSystem/Folder.swift
  Blank/Blank/Resources/ame.pdf
  Blank/Blank/Util/NavigationUtil.swift
  Blank/Blank/View/Common/ProgressStatusView.swift
  Blank/Blank/View/Home/FolderThumbnailView.swift
  Blank/Blank/View/Home/HomeView.swift
  Blank/Blank/View/Home/PhotoPickerRepresentedView.swift
  Blank/Blank/View/Home/PullToRefresh.swift
  Blank/Blank/View/Home/SelectFolderView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/View/ResultPage/ResultPageView.swift
  Blank/Blank/ViewModel/HomeViewModel.swift
  Blank/Blank/ViewModel/SelectFolderViewModel.swift
Labels: enhancement

#147 #146 design 뷰제목 및 알러트 단어 바꾸기
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/Extension/Color+.swift
  Blank/Blank/View/ImageView.swift
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/View/OverView/OverViewModalView.swift
  Blank/Blank/View/ResultPage/ResultPageView.swift
  Blank/Blank/View/TestPage/TestPageView.swift
  Blank/Blank/View/WordSelectView.swift
  Blank/Blank/ViewModel/OverViewModel.swift
Labels: design

#150 [feat] 131-feat-단어-시험전-암기를-위한-연습장-view제작
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/Assets.xcassets/DownLeftSizeLine.imageset/Contents.json
  Blank/Blank/Assets.xcassets/DownLeftSizeLine.imageset/DownLeftSizeLine.png
  Blank/Blank/Assets.xcassets/DownLeftSizeLine.imageset/DownLeftSizeLine@2x.png
  Blank/Blank/Assets.xcassets/DownLeftSizeLine.imageset/DownLeftSizeLine@3x.png
  Blank/Blank/Assets.xcassets/DownRightSizeLine.imageset/Contents.json
  Blank/Blank/Assets.xcassets/DownRightSizeLine.imageset/DownRightSizeLine.png
  Blank/Blank/Assets.xcassets/DownRightSizeLine.imageset/DownRightSizeLine@2x.png
  Blank/Blank/Assets.xcassets/DownRightSizeLine.imageset/DownRightSizeLine@3x.png
  Blank/Blank/Assets.xcassets/DrawingViewBackgroundImage.imageset/Contents.json
  Blank/Blank/Assets.xcassets/DrawingViewBackgroundImage.imageset/DrawingViewBackgroundImage.png
  Blank/Blank/Assets.xcassets/DrawingViewBackgroundImage.imageset/DrawingViewBackgroundImage@2x.png
  Blank/Blank/Assets.xcassets/DrawingViewBackgroundImage.imageset/DrawingViewBackgroundImage@3x.png
  Blank/Blank/Assets.xcassets/UpLeftSizeLine.imageset/Contents.json
  Blank/Blank/Assets.xcassets/UpLeftSizeLine.imageset/UpLeftSizeLine.png
  Blank/Blank/Assets.xcassets/UpLeftSizeLine.imageset/UpLeftSizeLine@2x.png
  Blank/Blank/Assets.xcassets/UpLeftSizeLine.imageset/UpLeftSizeLine@3x.png
  Blank/Blank/Assets.xcassets/UpRightSizeLine.imageset/Contents.json
  Blank/Blank/Assets.xcassets/UpRightSizeLine.imageset/UpRightSizeLine.png
  Blank/Blank/Assets.xcassets/UpRightSizeLine.imageset/UpRightSizeLine@2x.png
  Blank/Blank/Assets.xcassets/UpRightSizeLine.imageset/UpRightSizeLine@3x.png
  Blank/Blank/View/ExerciseView.swift
  Blank/Blank/View/OverView/OverView.swift
Labels: enhancement

#151 #148 feat 전체통계 기능 구현
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/Assets.xcassets/folderBackIcon.imageset/Contents.json
  Blank/Blank/Assets.xcassets/folderBackIcon.imageset/folderBackIcon.png
  Blank/Blank/Assets.xcassets/folderBackIcon.imageset/folderBackIcon2x.png
  Blank/Blank/Assets.xcassets/folderBackIcon.imageset/folderBackIcon3x.png
  Blank/Blank/Assets.xcassets/folderIcon.imageset/Contents.json
  Blank/Blank/Assets.xcassets/folderIcon.imageset/folderIcon.png
  Blank/Blank/Assets.xcassets/folderIcon.imageset/folderIcon2X.png
  Blank/Blank/Assets.xcassets/folderIcon.imageset/folderIcon3x.png
  Blank/Blank/Extension/Color+.swift
  Blank/Blank/Model/Presentable/WordStatistics.swift
  Blank/Blank/View/Home/FolderThumbnailView.swift
  Blank/Blank/View/Home/HomeView.swift
  Blank/Blank/View/Home/PDFThumbnailView.swift
  Blank/Blank/View/ImageView.swift
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OverView/OverVIewImageView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/View/OverView/OverViewModalView.swift
  Blank/Blank/View/OverView/StatModeIndexView.swift
  Blank/Blank/View/ResultPage/ResultPageView.swift
  Blank/Blank/View/TestPage/TestPageImageView.swift
  Blank/Blank/View/TestPage/TestPageView.swift
  Blank/Blank/View/WordSelectView.swift
  Blank/Blank/ViewModel/OverViewModel.swift
Labels: enhancement

#154 #152 design UI변경
  Blank/Blank/View/Home/FolderThumbnailView.swift
  Blank/Blank/View/Home/HomeView.swift
  Blank/Blank/View/Home/PDFThumbnailView.swift
  Blank/Blank/View/Home/SelectFolderView.swift
  Blank/Blank/View/ImageView.swift
  Blank/Blank/View/OverView/OverVIewImageView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/View/OverView/OverViewModalView.swift
  Blank/Blank/View/WordSelectView.swift
  Blank/Blank/ViewModel/HomeViewModel.swift
Labels: design

#156 [feat] overView spacer제거 , 기기별 좌표대응
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/View/ImageView.swift
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OCREdit/OCRImageView.swift
  Blank/Blank/View/OverView/OverVIewImageView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/View/ResultPage/ResultPageView.swift
  Blank/Blank/View/TestPage/TestPageImageView.swift
  Blank/Blank/View/TestPage/TestPageView.swift
  Blank/Blank/View/WordSelectView.swift
Labels: enhancement

#160 [fix] 오버뷰에서 pdf파일 이름이 너무 길지 않게 설정
  Blank/Blank/View/OverView/OverView.swift
Labels: bug
