Repository DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank, pull requests merged in 2023-10, with the labels that each got.

#11 [Feat] 코어 데이터 모델 추가
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/BlankApp.swift
  Blank/Blank/CoreData/Blank.xcdatamodeld/Blank.xcdatamodel/contents
  Blank/Blank/CoreData/Persistence.swift
  Blank/Blank/View/PersistenceView.swift
Labels: enhancement

#18 [Design] 모든 뷰 구현
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/Assets.xcassets/myImage.imageset/Contents.json
  Blank/Blank/Assets.xcassets/myImage.imageset/myImage.png
  Blank/Blank/Assets.xcassets/thumbnail.imageset/Contents.json
  Blank/Blank/Assets.xcassets/thumbnail.imageset/thumbnail.png
  Blank/Blank/BlankApp.swift
  Blank/Blank/View/ContentView.swift
  Blank/Blank/View/CorrectInfoView.swift
  Blank/Blank/View/HomeView.swift
  Blank/Blank/View/OCREditView.swift
  Blank/Blank/View/OverView.swift
  Blank/Blank/View/OverViewModalView.swift
  Blank/Blank/View/PDFThumbnailView.swift
  Blank/Blank/View/ResultPageView.swift
  Blank/Blank/View/ScribbleModalView.swift
  Blank/Blank/View/TestPageView.swift
  Blank/Blank/View/WordSelectView.swift
Labels: design

#22 [Design] Add checkmark
  Blank/Blank/Assets.xcassets/checkedCheckmark.imageset/Contents.json
  Blank/Blank/Assets.xcassets/checkedCheckmark.imageset/check2X.png
  Blank/Blank/Assets.xcassets/checkedCheckmark.imageset/check3X.png
  Blank/Blank/Assets.xcassets/checkedCheckmark.imageset/checkedCheckmark.png
  Blank/Blank/Assets.xcassets/emptyCheckmark.imageset/Contents.json
  Blank/Blank/Assets.xcassets/emptyCheckmark.imageset/empty2X.png
  Blank/Blank/Assets.xcassets/emptyCheckmark.imageset/empty3X.png
  Blank/Blank/Assets.xcassets/emptyCheckmark.imageset/emptyCheckmark.png
  Blank/Blank/View/HomeView.swift
Labels: design

#19 [Feat] HomeView: 파일 목록 가져오기, 섬네일 표시, 검색 기능
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/BlankApp.swift
  Blank/Blank/Dummy/DummyObjects.swift
  Blank/Blank/Extension/FileMananger+.swift
  Blank/Blank/Extension/UIImage+.swift
  Blank/Blank/Info.plist
  Blank/Blank/Model/File.swift
  Blank/Blank/Resources/blank.pdf
  Blank/Blank/Resources/horizontal.pdf
  Blank/Blank/Resources/sample.pdf
  Blank/Blank/Resources/toeic.pdf
  Blank/Blank/Util/PDFUtil.swift
  Blank/Blank/View/Home/DocumentPickerRepresentedView.swift
  Blank/Blank/View/Home/HomeView.swift
  Blank/Blank/View/OverViewModalView.swift
  Blank/Blank/View/PDFThumbnailView.swift
  Blank/Blank/ViewModel/HomeViewModel.swift
Labels: enhancement

#24 [Feat] #20 HomeView: 사진 라이브러리로부터 추가 기능
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/CoreData/Blank.xcdatamodeld/Blank.xcdatamodel/contents
  Blank/Blank/CoreData/Persistence.swift
  Blank/Blank/Util/PDFUtil.swift
  Blank/Blank/View/Home/HomeView.swift
  Blank/Blank/View/Home/PhotoPickerRepresentedView.swift
  Blank/Blank/View/PersistenceView.swift
Labels: enhancement

#30 [Feat] 파일 편집 기능 추가
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/Extension/CGRect+.swift
  Blank/Blank/Model/File.swift
  Blank/Blank/Model/Page.swift
  Blank/Blank/Model/Session.swift
  Blank/Blank/Model/Word.swift
  Blank/Blank/View/Home/HomeView.swift
  Blank/Blank/ViewModel/HomeViewModel.swift
Labels: enhancement

#33 #32 feat 파일을 뷰에 연결
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/BlankApp.swift
  Blank/Blank/View/Home/HomeView.swift
  Blank/Blank/View/OCREditView.swift
  Blank/Blank/View/OverView.swift
  Blank/Blank/View/OverViewModalView.swift
  Blank/Blank/View/ResultPageView.swift
  Blank/Blank/View/TestPageView.swift
  Blank/Blank/View/WordSelectView.swift
  Blank/Blank/ViewModel/OverViewModel.swift
  Blank/Blank/ViewModel/del.swift
Labels: enhancement

#35 34 design imageview를 pinchzoomview로 변경
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/Model/Page.swift
  Blank/Blank/View/CurrentPageView.swift
  Blank/Blank/View/ImageView.swift
  Blank/Blank/View/OCREditView.swift
  Blank/Blank/View/OverView.swift
  Blank/Blank/View/PinchZoomView.swift
  Blank/Blank/View/ResultPageView.swift
  Blank/Blank/View/TestPageView.swift
  Blank/Blank/View/WordSelectView.swift
  Blank/Blank/ViewModel/OverViewModel.swift
Labels: enhancement, design

#37 [Feat] #10 core data 기본 세팅
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/CoreData/Blank.xcdatamodeld/Blank.xcdatamodel/contents
  Blank/Blank/CoreData/CDService.swift
  Blank/Blank/CoreData/Persistence.swift
  Blank/Blank/CoreData/README.md
  Blank/Blank/Extension/CGRect+.swift
  Blank/Blank/Extension/Int+.swift
  Blank/Blank/Extension/String+.swift
  Blank/Blank/Model/Session.swift
  Blank/Blank/Model/Word.swift
  Blank/Blank/View/PersistenceView.swift
Labels: enhancement

#41 #38 core data api
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/CoreData/Blank.xcdatamodeld/Blank.xcdatamodel/contents
  Blank/Blank/CoreData/CDService.swift
  Blank/Blank/Model/Page.swift
  Blank/Blank/Model/Session.swift
  Blank/Blank/Model/Word.swift
  Blank/Blank/View/Persistence/APICRUDView.swift
  Blank/Blank/View/Persistence/PersistenceView.swift
Labels: enhancement

#56 #44 data model implement
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/View/CorrectInfoView.swift
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/Persistence/ScoringTestView.swift
  Blank/Blank/View/ResultPageView.swift
  Blank/Blank/View/TestPage/TestPageView.swift
  Blank/Blank/ViewModel/ScoringViewModel.swift
Labels: enhancement

#65 #60 design 버튼강조하기
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/View/Home/HomeView.swift
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/View/OverView/OverViewModalView.swift
  Blank/Blank/View/PDFThumbnailView.swift
  Blank/Blank/View/ResultPageView.swift
  Blank/Blank/View/TestPage/TestPageView.swift
  Blank/Blank/View/WordSelectView.swift
  Blank/Blank/ViewModel/HomeViewModel.swift
  Blank/Blank/ViewModel/OverViewModel.swift
Labels: design

#64 [Feat] WordSelectView의 Alert을 Toast로 바꿈
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Blank/Blank/View/WordSelectView.swift
Labels: enhancement

#67 [Refactor] Model 일부 변경 및 새로운 ViewModel 적용
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/BlankApp.swift
  Blank/Blank/CoreData/CDService.swift
  Blank/Blank/Dummy/DummyObjects.swift
  Blank/Blank/Model/File.swift
  Blank/Blank/Model/Page.swift
  Blank/Blank/Model/Session.swift
  Blank/Blank/View/CorrectInfoView.swift
  Blank/Blank/View/Home/HomeView.swift
  Blank/Blank/View/ImageView.swift
  Blank/Blank/View/OCREdit/OCREditView.swift
  Blank/Blank/View/OCREdit/OCRImageView.swift
  Blank/Blank/View/OCREdit/OCRPinchZoomView.swift
  Blank/Blank/View/OCREdit/TextView.swift
  Blank/Blank/View/OverView/OverView.swift
  Blank/Blank/View/PDFThumbnailView.swift
  Blank/Blank/View/Persistence/APICRUDView.swift
  Blank/Blank/View/PinchZoomView.swift
  Blank/Blank/View/ResultPageView.swift
  Blank/Blank/View/TestPage/TestPageImageView.swift
  Blank/Blank/View/TestPage/TestPagePinchZoomView.swift
  Blank/Blank/View/TestPage/TestPageView.swift
  Blank/Blank/View/WordSelectView.swift
  Blank/Blank/ViewModel/HomeViewModel.swift
  Blank/Blank/ViewModel/OverViewModel.swift
  Blank/Blank/ViewModel/ScoringViewModel.swift
  Blank/Blank/ViewModel/TextViewModel.swift
  Blank/Blank/ViewModel/WordSelectViewModel.swift
Labels: enhancement

#70 [Feat] 채점 로직 변경
  Blank/Blank/ViewModel/ScoringViewModel.swift
Labels: enhancement

#71 [Feat] pop to Root 기능 구현
  Blank/Blank.xcodeproj/project.pbxproj
  Blank/Blank/Util/NavigatioinUtil.swift
  Blank/Blank/View/ResultPageView.swift
Labels: enhancement
